{{- if or .Values.serviceAccount.create .Values.global.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cf-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.image.credentials }}
imagePullSecrets:
- name: {{ template "cf-operator.serviceAccountName" . }}-pull-secret
{{- end }}
{{- end }}

{{- if .Values.global.rbac.create }}
---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: {{ template "cf-operator.fullname" . }}-cluster
    subjects:
    - kind: ServiceAccount
      name: {{ template "cf-operator.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
    roleRef:
      kind: ClusterRole
      name: {{ template "cf-operator.fullname" . }}-cluster
      apiGroup: rbac.authorization.k8s.io

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: {{ template "cf-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
    subjects:
    - kind: ServiceAccount
      name: {{ template "cf-operator.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
    roleRef:
      kind: Role
      name: {{ template "cf-operator.fullname" . }}-webhook
      apiGroup: rbac.authorization.k8s.io
  # Temporarily create a ClusterRoleBinding for cluster-admin until we can figure out what are exactly the
  # minimum permissions required for deploying the operator
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: {{ template "cf-operator.fullname" . }}-cluster-admin
    subjects:
      - kind: ServiceAccount
        name: cf-operator-quarks
        namespace: cf-operator
      - kind: ServiceAccount
        name: cf-operator-quarks-job
        namespace: cf-operator
      - kind: ServiceAccount
        name: cf-operator-quarks-secret
        namespace: cf-operator
      - kind: ServiceAccount
        name: cf-operator-quarks-statefulset
        namespace: cf-operator
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
{{- end }}
